cache:
  key: ${CI_PROJECT_NAME}
  paths: # cache everything so that unnecessary recompilation is avoided
    - lib
    - src
    - test
    - CMakeLists.txt
    - Doxyfile.in
job:
  image: pjknowles/opensuse
  script:
    - procs=$(lscpu -p | egrep -v '^#' | wc -l || echo 1); echo $procs processors available
    - TOP=$PWD
    - git checkout $CI_COMMIT_SHA # because of cache
    - git reset --hard
    - git clean -f src lib test
    - cd $TOP; BUILD=build; mkdir -p $BUILD && cd $BUILD && pwd && cmake -DMPIOPTIONS="--allow-run-as-root" $TOP ; cmake --build . -- -j ${procs} ; cd test;  ctest -V -j ${procs}

